-- Calculate the application category from the application type
{% macro application_category_parser(application_type)  -%}
CASE
            WHEN LOWER("{{ application_type }}") IN ('smartcast'
                                                ,'has_player'
                                                ,'tizen'
                                                ,'xfinity'
                                                ,'fairplay'
                                                ,'webos'
                                                ,'exoplayer'
                                                ,'abstract method'
                                                ,'tv web'
                                                ,'skyq'
                                                ,'mdk_sky_q'
                                                ,'roku tv'
                                                ,'shaka'
                                                ,'netcast'
                                                ,'orsay'
                                                ,'opera tv'
                                                ,'chromecast'
                                                ,'mdk_android_tv'
                                                ,'hisense'
                                                ,'xbox one'
                                                ,'playstation 4'
                                                ,'playstation 3'
                                                ,'apple tv'
                                                ,'toshiba tv'
                                                ,'panasonic tv'
                                                ,'sony tv'
                                                ,'android tv'
                                                ,'hisensejp'
                                                ,'sonyceb'
                                                ,'mdk_webmaf'
                                                ,'funai') THEN 'Living Room'
        WHEN LOWER("{{ application_type }}") IN ('ios', 'android') THEN 'Mobile'
        WHEN LOWER("{{ application_type }}") = 'web' THEN 'Web'
        ELSE 'Others'
        END
{%- endmacro %}
